name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t deshmukhmath/wisecow:latest .
        docker push deshmukhmath/wisecow:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f wisecow-deployment.yaml
        kubectl apply -f wisecow-service.yaml
